// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgycvfzkzwybrmduitld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpneWN2Znprend5YnJtZHVpdGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTk0MjUsImV4cCI6MjA2NDU5NTQyNX0.VRvQHBsvi8bCC9hqdc_ucBZjw3vUT3ZBoNuvzCaGZG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);